### ISSUE TITLE
Dropdown immediately disappears after click

### ISSUE THREAD

**Issue by yglodt** [shafi-sahal/MatSelectSearch#1]
Hello,

first let me thank you for your component which is really nice!

I am using it in a form inside a mat-dialog, and the data for the dropdown is loaded from the backend in ngOnInit like this:
```
public organizations: any[] = [];
public filteredOrganizations: any[] = [];

public ngOnInit() {
	this.adminService.getOrganizations().subscribe((result) => {
		this.organizations = result.data;
		this.filteredOrganizations = this.organizations.slice();
		// this.filteredOrganizations = this.organizations; // makes no difference
	});
}
```

The template code is here:
```
<mat-form-field>
	<mat-label>Organization</mat-label>
	<mat-select #organizationIdSelect formControlName="mappedOrganizationId" required>
		<mat-option>
			<lib-mat-select-search [list]="organizations" [searchProperties]="['id', 'name']" [clearSearchInput]="true" (filtered)="filteredOrganizations = $event"></lib-mat-select-search>
		</mat-option>
		<mat-select-trigger>{{ organizationIdSelect.value }}</mat-select-trigger>
		<mat-option *ngFor="let o of filteredOrganizations" [value]="o.id">
			{{ o.name }}
		</mat-option>
	</mat-select>
</mat-form-field>
```

When I click the dropdown, the full list of mat-options briefly appears (~250ms...) and then disappears. What remains is the empty "Search" bar, and typing into it does not do anything. There is no error in the javascript console.

Is there an issue with async data loading, or did I do anything wrong?

**Comment by shafi-sahal** [comment]
Thanks for reporting the issue!!
The cause:
1) The component is loaded before fetching the users from the backend and hence the 'organizations 'passing to the component 
    is an empty array.
    ```public organizations: any[] = [] //empty array initialization```

Solution:
While using async data load the component only when there is data in the variable.
There are 2 methods:
1)  Use definite assignment and ngIf="users"
     
     ts file
     ```public organizations!: any[];  // definite assignment``` 
    
     template file
    ```<lib-mat-select-search *ngIf="users" [list]="organizations" [searchProperties]="['id', 'name']" [clearSearchInput]="true" 
    (filtered)="filteredOrganizations = $event"></lib-mat-select-search>```

                                                                          OR

2) Use ngIf="users.length > 0"
      template file
    ```<lib-mat-select-search *ngIf="users.length > 0" [list]="organizations" [searchProperties]="['id', 'name']" 
    [clearSearchInput]="true" 
    (filtered)="filteredOrganizations = $event"></lib-mat-select-search>```

Hope it works...
Tell me whether it works or not and if you face any other issues.

**Comment by shafi-sahal** [comment]
Thanks for reporting the issue!!
The cause:
1) The component is loaded before fetching the organizations from the backend and hence the 'organizations 'passing to the component 
    is an empty array.
    ```public organizations: any[] = [] //empty array initialization```

Solution:
While using async data, load the component only when there is data in the variable.
There are 2 methods:
1)  Use definite assignment and ngIf="organizations"
     
     ts file
     ```public organizations!: any[];  // definite assignment``` 
    
     template file
 ```
    <lib-mat-select-search *ngIf="organizations" [list]="organizations" [searchProperties]="['id', 'name']" [clearSearchInput]="true" 
    (filtered)="filteredOrganizations = $event"></lib-mat-select-search> 

```

 OR                                                                      

2) Use ngIf="organizations.length > 0"
      template file
```
   <lib-mat-select-search *ngIf="organizations.length > 0" [list]="organizations" [searchProperties]="['id', 'name']" 
    [clearSearchInput]="true" 
    (filtered)="filteredOrganizations = $event"></lib-mat-select-search> 
```

Hope it works...
Tell me whether it works or not and if you face any other issues, tell that too.

**Comment by yglodt** [comment]
Hello Shafi,

thank you for your help, now it works (using solution 2)

**Comment by shafi-sahal** [comment]
Thanks for the response!!
