### ISSUE TITLE
Async data set does not work

### ISSUE THREAD

**Issue by Ashden** [shafi-sahal/MatSelectSearch#11]
Hello,

I've tried to use this component with an async list, and in the research, I noticed that the list is only set in the constructor, so any async data set used cannot update the component. 
You can notice the issue in this example: https://stackblitz.com/edit/github-jdmmaq?file=src/app/app.component.ts
Is it possible to allow async lists?

Thanks.

**Comment by shafi-sahal** [comment]
Thanks for reporting the issue!!
Let me check it.

**Comment by valeratumashsa** [comment]
Also trying to update the list once it is initialised and `MatSelectSearch` doesn't seem to pick them up, keep seeing the list that was used on component init.
Potentially, adding `ngOnChanges` to check `@Input() list` updates would fix the issue, @shafi-sahal ?

**Comment by shafi-sahal** [comment]
Thanks for the suggestion!!!. If you are free you can check it and send a PR. Anyway, I will be fixing it in the next release.

**Comment by reezpatel** [comment]
I did a workaround for now, (I know it's not the prettiest solution, but it works!!)

```
component.html
-----
<lib-mat-select-search #dropdown>

component.ts
-----
(this.dropdown as any).fullList = this.cities;
(this.dropdown as any).searcher.initSearch(this.cities, ['title']);
(this.dropdown as any).filtered.emit(this.cities);
```

this updates the inner list (which I still don't get, why we need to keep a copy of it internally??)
