### ISSUE TITLE
Upgrade to Angular 14

### ISSUE THREAD

**Issue by yglodt** [shafi-sahal/MatSelectSearch#12]
Hello,

please upgrade MatSearchSelect requirements to Angular 14 : )

Thanks

**Comment by shafi-sahal** [comment]
Thanks yglodt for pointing it out. Will do it :+1:

**Comment by yglodt** [comment]
Hello Shafi, any chance you can look into this?

Probably only a change to package.json is required.

**Comment by alexis-mrc** [comment]
if it's possible to do a release for angular 13 and another for angular 14, it would be perfect
Thank you !

**Comment by yglodt** [comment]
Maybe there is a way to create the component without a specific dependency, or with >=13 or something, which would be good since it would save you from running behind every Angular release.

**Comment by alexis-mrc** [comment]
I am not sure of this solution.
Angular major updates can include breaking changes that may break the library.

I think taking a little time every 6 months to check the compatibility is the correct solution.
I may do a pull request in the next days

**Comment by shafi-sahal** [comment]
Hi everyone. Sorry for the delay. I was working on tight schedules for some time. I have updated the package to v13 and then v14.
As @avelow told, major updates are not recommended by angular, so the updating was done progressively.
mat-select-search 1.2.6 will be angular v13 and mat-select-search 1.2.7 will be angular v14.

Thanks guys for your suggestions and support
