### ISSUE TITLE
this.subscriptions.add(...) is undefined

### ISSUE THREAD

**Issue by Intrpt** [shafi-sahal/MatSelectSearch#14]
Hi guys,

when using` lib-mat-select-search `
```
               <mat-form-field>
                <mat-label>Select Language</mat-label>
                 <mat-select #languageSelect multiple>
                  <mat-select-trigger>{{languageSelect.value}}</mat-select-trigger> 
                    <mat-option>
                    <lib-mat-select-search
                      [list]="languages"
                      [searchProperties]="['name','code']"
                      (filtered)="filteredLanguages = $event">
                    </lib-mat-select-search>
                  </mat-option> 
            
                  <mat-option *ngFor="let language of filteredLanguages" [value]="language['code']">
                    {{language['name']}}
                  </mat-option>  
            
                </mat-select>
              </mat-form-field> 
```

I'm getting a `this.subscriptions.add(...) is undefined` error within `ngAfterViewInit`
![grafik](https://user-images.githubusercontent.com/34034087/156158005-647c06be-14ae-411c-a00d-c3059e092868.png)

So I guess its coming from here:
https://github.com/shafi-sahal/MatSelectSearch/blob/cbbbd0b7217ce68b59341595eb6dc8d1c304916b/projects/mat-select-search/src/lib/mat-select-search.component.ts#L62

rxjs v6.6.7

**Comment by pstyrna** [comment]
Subscription.add is no longer returning Subscription so author cannot chain .add like he did there.
