### ISSUE TITLE
Cannot find module or its corresponding type declarations

### ISSUE THREAD

**Issue by Rick-1242** [shafi-sahal/MatSelectSearch#17]
I've encounered an issue that I can't seem to solve, after running `npm install mat-select-search` when I try to import it in the module  `import { MatSelectSearchModule } from 'mat-select-search';` the termial errors out saying :

> Cannot find mat-select-search module or its corresponding type declarations

I was able to solve that by adding `// @ts-igonre` like so:

// @ts-igonre
import { MatSelectSearchModule } from 'mat-select-search';

After that I tried adding it to the imports array of the @NgModule. When i do that angular is no longer able to recognise the other imports and everything brakes. I tryed running `npm install @types/mat-select-search --save-dev` It says that the type declarations for this module don't exist.

**Comment by yglodt** [comment]
I can confirm I have this issue too. I could only solve it by going back to v1.1.3. I did not try going to 1.2.3 or 1.2.4.

**Comment by shafi-sahal** [comment]
What's the version on which you guys observed the issue?

**Comment by shafi-sahal** [comment]
Hi, fixed the issue
Try the new version v1.2.21.
Hope it works!!!

**Comment by yglodt** [comment]
> What's the version on which you guys observed the issue?

I had the issue with 1.2.6 and 1.2.7.

**Comment by yglodt** [comment]
> Hi, fixed the issue
> Try the new version v1.2.21.
> Hope it works!!!

Yes, the error has disappeared. Thank you!

**Comment by Rick-1242** [comment]
> What's the version on which you guys observed the issue?

what used to be the lates  v1.2.7 one one since I'm using angular 14

**Comment by Rick-1242** [comment]
Yep, it works now 
thanks

**Comment by adcoding** [comment]
It's not working. I'm using the latest version of angular and mat-select-search
I got this errors:
Cannot find name 'BrowserAnimationsModule'.
Cannot find name 'MatSelectModule'.
Cannot find name 'MatCardModule'.
