### ISSUE TITLE
mat-option value is used as label instead of tag content

### ISSUE THREAD

**Issue by yglodt** [shafi-sahal/MatSelectSearch#2]
Hello,

I found an issue with the mat-option containing the dropdown values.

With your example on StackBlitz, I would like to change it to use ```[value]="country.code"``` and not ```[value]="country.name"```. Here your original code with a comment of mine:

```
<mat-card>
  <mat-form-field>
    <mat-label>Select a country</mat-label>
    <mat-select #countrySelect>
      <mat-option>
        <lib-mat-select-search
        [list]="countries"
        [searchProperties]="['dialCode', 'name']"
        (filtered)="filteredCountries = $event">
      </lib-mat-select-search>
      </mat-option>
      <mat-select-trigger>{{countrySelect.value}}</mat-select-trigger>
      <mat-option *ngFor="let country of filteredCountries" [value]="country.name"><!-- here I need country.code -->
        <div class="country-container">
          <p>{{country.name}}</p><p>{{country.dialCode}}</p>
        </div>
      </mat-option>
    </mat-select>
  </mat-form-field>
</mat-card>
```

The usage of country.code is necessary in my case, because I use ```formControlName``` on  the ```mat-select``` and need to bind the input value to ```country.code``` and not ```country.name```.

How could this be done?

**Edit** I forgot to mention the actual issue: When using ```[value]="country.code"```, on selection, the dropdown shows ```country.code``` as label and not ```country.name``` (which is what a pure ```mat-select``` does).

Thank you in advance.

**Comment by shafi-sahal** [comment]
I have checked the issue but it works fine.
As per my understanding, you want the mat-option to display the country name but the value should be country code. Isn't it?

**Comment by yglodt** [comment]
> As per my understanding, you want the mat-option to display the country name but the value should be country code. Isn't it?

Yes, exactly.

Here is the issue visible after I modified the template to use country.code, and selected the country "Luxembourg":

![image](https://user-images.githubusercontent.com/489599/126144218-f012f198-7945-447b-a2ba-7fc5b1c45e61.png)

**Comment by shafi-sahal** [comment]
Ok, I got it.
Remove the ```<mat-select trigger>```
Mat select trigger is for setting the value to display after selection.
In your case, it is not needed.

**Comment by yglodt** [comment]
Perfect, now it works as expected.

Thank you very much Shafi.

**Comment by shafi-sahal** [comment]
Welcome and glad to know the issue is solved.
