### ISSUE TITLE
Implementation with form array

### ISSUE THREAD

**Issue by Manmohabe** [shafi-sahal/MatSelectSearch#3]
I appreciate this awesome work although i have a small issue when using it with form array. 
![selectsearch](https://user-images.githubusercontent.com/42378971/131221748-6ed875f1-7d10-4e1c-b7a3-7570ab7db4e7.PNG)
Whenever i try to search row 2 with the a different item, row 1 becomes empty. The problem is with the filteredlist since its being shared between multiple rows. am referring to the Item/Account column

**Comment by shafi-sahal** [comment]
Thank you for sharing the issue!!
Yeah, it's the problem with shared filteredList. Try making filteredList as a 2d array and use an index to take the appropriate filteredList for each row. Are you using a ngFor for repeating rows. If that is so just use the 'index as i' in the loop to take the appropriate filteredList.

```
// Push a new list to the array when a row is added.
filteredList = [list, list, list];

// in the lib-mat-select-search
(filtered) = "filteredList[index] = $event"
```

Hope it works.
Share if there is any problem.

**Comment by Manmohabe** [comment]
Thanks for your reply.
This is very clever i will try it and let you know. The only issue i think of is when getting the saved information of this form from the server which means i will need to initialize 2d array for each row

**Comment by shafi-sahal** [comment]
You may not need to initialize 2d array for each row.
Try this:
```
//Initialize a 2d array
filteredList : Array<YourListType>[]= [];

//Make a function to initialize the list only for the index of the row where the user clicked for the dropdown
onDropDownStarted(index: number): void {
   filteredList[index] = list;
}

// In the template
<mat-select (click)="onDropDownStarted(index)"></mat-select>
```

So, you can initialize the list value only when a user clicks on the particular dropdown in the row.
I hope it's what you raised the concern about.
Let me know if it works or not.

**Comment by Manmohabe** [comment]
> I hope it's what you raised the concern about

Nop, So far everything works fine except for the case where i want to edit the form. Binding back the saved data from the server
This is part of my template code 
`<mat-select formControlName="accountItemID" (selectionChange)="linehaschanged($event,rowIndex)">`
 
```
 <mat-option *ngIf="lineitemlist.length>0">
                    <lib-mat-select-search
                      [list]="lineitemlist"
                      [searchProperties]="['lineItemCode', 'lineItemName']"
                      [clearSearchInput]=true
                      (filtered)="filteredItemAccountList[rowIndex] = $event">
                    </lib-mat-select-search>
                  </mat-option>
                  <mat-option *ngFor="let d of filteredItemAccountList[rowIndex]" [value]=d.lineItemID  ngForTrackBy:d.lineItemID>
                    {{d.lineItemCode}} {{d.lineItemName}}
                  </mat-option>
```
This field appear empty and the only way to deal with it is by initializing the 2d array for each row. Your suggested solution means the user must click on each row for the field to get updated which may not be correct. I think the best option can be you returning the full list during initial load  (filtered)="filteredItemAccountList[rowIndex] = $event"> you can have a setting for this similar to the [clearSearchInput]=true meaning the filteredItemAccountList will self initialize

**Comment by shafi-sahal** [comment]
Yeah, now I get your question. So you are saying that while loading the already saved form from the server, the selected value is not displayed by default. Isn't it? Also, how do you understand how many rows are there saved? Is there any value stored for that in server or what logic are you applying?

**Comment by Manmohabe** [comment]
Yeah, I have a logic that populates this form.
 ```
updateentries(result:InvoiceHeaderDto | OrderHeaderDto,reduceQuantity:boolean,FormAction:FormActions,setMaximumQuantity:boolean){
     this.FormAction=FormAction;
    const userCtrl = this.Childform.get('Invoices') as FormArray;
    userCtrl.clear();
        result.invoices.forEach(element => {
          var remaingqty=reduceQuantity?(element.quantity-element.qtReversed):element.quantity;
          var tax=reduceQuantity?this.calculateTax(element.amountInclTax,element.taxRate,element.actualAmount,remaingqty):element.taxAmount;
          userCtrl.push( this.formBuilder.group({
            invoiceID:[element.invoiceID],
            isItem:[element.isItem],
            accountItemID:[element.accountItemID,[Validators.required]],
            actualAmount:element.actualAmount,
            baseAmount:[element.baseAmount,[Validators.required,Validators.min(1)]],
            description:[element.description,[Validators.required]],
            discountRate:[element.discountRate,[Validators.required,Validators.min(0),Validators.max(99)]],
            expenseAccountID:element.expenseAccountID, 
            incomeAccountID:element.incomeAccountID,
            inventoryAccountID:element.inventoryAccountID,
            itemType:element.itemType,
            taxAccountID:[element.taxAccountID],
            taxRate:element.taxRate,
            warehouseID:element.isItem?[element.warehouseID,[Validators.required]]: element.warehouseID,
            measurementCode:[element.measurementCode,[Validators.maxLength(10)]],
            taxID:element.taxID,
            amountInclTax:element.amountInclTax,
            quantity:[remaingqty,setMaximumQuantity?[Validators.required,Validators.min(1),Validators.max(remaingqty)]:[Validators.required,Validators.min(1)]],
            taxAmount:tax,
            totalAmount:this.calculatesum(element.amountInclTax,element.actualAmount,remaingqty,tax),
          }))
        });
      //Disable all controls in readonly mode
      if (FormAction==FormActions.VieworEdit) {
        if (this.displayedColumns.includes('actions')) {
          this.displayedColumns.pop();
        }
        this.Childform.disable();
      }

      this.datasource=new MatTableDataSource(userCtrl.value);
  }
```

I know i can hook up the initialization in this method but when getting this data here i still dont have the lineitemlist loaded
since they depend on the branchID as shown below
```
  this.form.get('branchID').valueChanges.subscribe(result=>{
      if (result!=undefined) {
        this.childinvoice.getlineitems(result);
      }
    })
```
This is the reason am doing this  <mat-option *ngIf="lineitemlist.length>0">. In short the during editing the lineitemlist is loaded after getting the saved data

**Comment by shafi-sahal** [comment]
So, it's like first you fetch data related to the form, then you load lineitemlist. Isn't it?
So, when does the branch id gets loaded? Are you fetching it from the server?

**Comment by Manmohabe** [comment]
This is a one to many relationship, I have a parent component and a child component
 Parent component contains fields such such branchID, customerID, date etc The child component handles the lineitems (Manipulation of the lineItems etc), The child component is used by many parent components (This is a finance system therefore the sales invoce, purchase invoice, credit note etc uses the same child component). During editing or viewing a sales invoice i load it with its invoice number from the server (This is a one to many json format parent component data including the child component data). I do the parent component binding and pass the rest to child component binding through this function 
`updateentries(result:InvoiceHeaderDto | OrderHeaderDto,reduceQuantity:boolean,FormAction:FormActions,setMaximumQuantity:boolean)` therefore the lineitemslist is loaded only after the binding of the branchID in the parent component is done as shown above.

**Comment by shafi-sahal** [comment]
So can you call updateentries only after the lineitemslist is loaded?

**Comment by Manmohabe** [comment]
That's tricky i don't know how to do that since am using observables when querrying the server. I think  i will have to create a directive that will notify when this is resolved
```
<mat-option *ngIf="lineitemlist.length>0">
                    <lib-mat-select-search
                      [list]="lineitemlist"
                      [searchProperties]="['lineItemCode', 'lineItemName']"
                      [clearSearchInput]=true
                      (filtered)="filteredItemAccountList[rowIndex] = $event">
                    </lib-mat-select-search>
                  </mat-option>
```
Then i can attach a method to initialize each row on the callback. Although i hoped this library was able to return the full list when it loads ((filtered)="filteredItemAccountList[rowIndex] = $event")

**Comment by shafi-sahal** [comment]
Why I am not jumping to include it in library is because of some reasons.
1) The library should be lightweight. So add features only if necessary.
2) Considering the simple responsibility, the library's job should only be searching and optimizing the search. Just give a list, it searches through it and gives the filtered list.
 
So, if the issue can be solved easily then it is better not to put it in the library. 
So, let's try first if it can be solved easily.

Also, can you tell how will you implement this feature if you were to write the code in the library? What are your suggestions?
Like, how can the library know if it has to return 2 lists or 3 lists ?

**Comment by shafi-sahal** [comment]
I think you can call the updateentries in the place where you retrieve the branchID through the observable. So, you cal the server for BranchId using an observable. Inside the callback function call the updateentries, so you can get lineitemslist before calling updateentries. Isn't it?

**Comment by Manmohabe** [comment]
> Also, can you tell how will you implement this feature if you were to write the code in the library? What are your suggestions?
> Like, how can the library know if it has to return 2 lists or 3 lists ?

I will just emit this event
`@Output() filtered = new EventEmitter<Record<string, string>[]>()`
on the  ngAfterViewInit(): void  hook with the input list. This will sort the issue above. Then i can have an input parameter which by default is false. Emit only if true. This means this code will initialize filteredItemAccountList with the full list 
 on the index (filtered)="filteredItemAccountList[rowIndex] = $event".

**Comment by shafi-sahal** [comment]
Yeah, That sounds nice. Thank you.
I will try it. Meanwhile if you feel like to contribute, just file a simple PR

**Comment by shafi-sahal** [comment]
Can you test it in your machine? So if the issue is solved you just file a PR.

**Comment by Manmohabe** [comment]
Thanks for you time i will

**Comment by shafi-sahal** [comment]
Thanks for your patience and time. Your solution was intelligent. My thoughts were not going to that side.

**Comment by Manmohabe** [comment]
Please check your mail am facing some few issues with the project. shafisahal99@gmail.com
