### ISSUE TITLE
Adding Input Placeholder

### ISSUE THREAD

**Issue by ghost** [shafi-sahal/MatSelectSearch#8]
I think it will be a nice feature to add an input Placeholder to manage multi-language

**Comment by shafi-sahal** [comment]
Thanks for the suggestion.!!!
Do you have any experience in working on multi-language?

**Comment by alexis-mrc** [comment]
The ability to let the user specify his own placeholder is the easiest and the best.

For exemple, the user could want to specify the search like "Search by Zip code" and you can't handle this in the component.
This way, you don't have to handle multi-language. It's the user problem to know which language he has to use in the placeholder. 

Something like a placeholder @Input would be perfect:
```
                <lib-mat-select-search
                  placeholder="Search in your task"
                  [list]="(tasksForSelect$ | async)!"
                  [searchProperties]="['displayLabel']"
                  (filtered)="setFilteredTasks($event)">
                </lib-mat-select-search>
```

If you don't have time, i may be able to try it during 01/2022

**Comment by shafi-sahal** [comment]
Yeah okay...Got it. Sorry I missed the message.
If you can try it then proceed so that it can be implemented accordingly how you want it.
If not any way I will do it but may take a little bit of time.

**Comment by Jorgersoares** [comment]
Hey Shafi I have created a pr for this issue, please check it out! https://github.com/shafi-sahal/MatSelectSearch/pull/13

**Comment by shafi-sahal** [comment]
Hey, sorry for the late replies, Have been a little busy recently.
Thank you so much for the contribution. I will merge it.
